# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170917_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
