# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Price',
            field=models.IntegerField(default=0),
        ),
    ]
