# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
