# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20171224_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_Date', models.DateField(default=datetime.date.today)),
                ('order_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
                ('order_Products', models.ManyToManyField(to='store.Product')),
            ],
        ),
    ]
