# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20180101_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_Customer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_Products',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
