# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
