# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_Products',
            field=models.ManyToManyField(blank=True, to='store.Product'),
        ),
    ]
