# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20180121_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='order_Id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderproducts',
            old_name='product_Id',
            new_name='product',
        ),
    ]
