# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20180122_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_Total',
            field=models.IntegerField(default=0),
        ),
    ]
