# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20180122_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_Total',
            field=models.FloatField(default=0),
        ),
    ]
